name: 'my_blog_analytics_dbt'
version: '1.0.0'

profile: 'my_blog_analytics_dw'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  my_blog_analytics_dbt:
    # Applies to all files under models/example/
    example:
      +materialized: table